import subprocess
import json

playlists = {
    # "bou&hedex": [
    #     'boudnb',
    #     'hedexuk'
    # ],
    # "dubstep": [
    #     'virtual-riot',
    #     'soltansound',
    #     'joolnoise',
    #     'eptic',
    #     'neversaydie',
    # ],
    "dnb": [
        'boudnb',
        'hedexuk',
        'kmotionzuk',
        'basstripper',
        'simula',
        'subfocus',
        'netsky',
        'deltaheavyuk',
        'noisia',
        'metrik',
        'dimension_uk',
        'wilkinsonuk'
    ],
    # "lofi": [
    #     'jinsangbeats',
    #     'idealismus',
    #     'ldre',
    #     'lindecis',
    #     'sleeepyfish',
    #     'birocratic',
    #     'sweepsbeats',
    #     'elijahwho',
    #     'fujitsu'
    # ],
    # "synthwave": [
    #     "voyage_synths",
    #     "kabesmusic",
    #     "hotelpoolsmusic",
    #     "downtownbinary",
    #     "virtuamusic",
    #     "viq-sc",
    #     "protocols-music",
    #     "davz-music",
    #     "oddlingmusic",
    #     "lofi_girl",
    #     "monolism-music",
    #     "alis_on",
    #     "krosia",
    #     "emil-rottmayer",
    #     "de-ceuster-jasper",
    #     "foudroie",
    #     "soundgosweden",
    #     "girlfromnowheremusic",
    #     "nitewalk-sc",
    #     "departure-sc",
    #     "lemetroid",
    #     "geromillan",
    #     "unfound",
    #     "kingpalm-music",
    #     "megasmusics",
    #     "xtract-music",
    #     "graeda-music",
    #     "ne0ngalaxy",
    #     "evans22863",
    #     "novussana",
    #     "forhill-music",
    #     "tibeauthetraveler",
    #     "djmartinroth",
    #     "caspromusic",
    #     "kingpalmmusic",
    #     "voj_official",
    #     "axl-rhodes",
    #     "mo_ure",
    #     "carlights_neoncity",
    #     "sequenzamusica",
    #     "worldcomplete",
    #     "evansgleb",
    #     "feature_phone",
    #     "introspektro",
    #     "spheressynth",
    #     "user-664126351-710491316",
    #     "obiowave",
    #     "digitalhotline",
    #     "frmsound",
    #     "sub-morphine",
    #     "bvsmv",
    #     "user-41376936",
    #     "theofficiallobst",
    #     "mxjp0",
    #     "amadeus-vegas",
    #     "timeaway",
    #     "playoldmusic",
    #     "jobe-swe",
    #     "yu-utsu",
    #     "space-cassette-music",
    #     "hypixi",
    #     "miragesynths",
    #     "fractalmanmusic",
    #     "corp81",
    #     "rosentwig",
    #     "girlfriendrecords",
    #     "realfujii",
    #     "master-max-2004",
    #     "theredwhit",
    #     "vokonmusic",
    #     "alpharoom",
    #     "space-sailors-music",
    #     "ivemduvmusic",
    #     "kattch",
    #     "creaturegallery"
}

subprocess.run(['py', 'collect-ids.py', json.dumps(playlists)])